### PR TITLE
WIP: Persist the LDAP connection

### PR DESCRIPTION
**Pull request by Meatballs1**
I have even left in my `Conncetion` typo

### CODE REVIEW

**Comment by rvazarkar** [comment]
I'm surprised this actually works. I was under the impression that the paging would get all sorts of messed up if you did this. 

I'm going to do some testing with this to see if its workable

**Comment by rvazarkar** [comment]
Also, we have to make ldap connections to other domains, so this would definitely break that. Some work will have to be done to make sure that ldap connections for each domain are maintained, instead of just for one.

**Comment by Meatballs1** [comment]
Yeah might need to be a bit cleverer if you are doing per domain. I would have thought the paging is per search however.

**Comment by rvazarkar** [comment]
Did you validate that you get the same amount of data with the connection caching?

**Comment by Meatballs1** [comment]
Yes - but I was only doing 'Group' query rather than 'All'.

**Comment by rvazarkar** [comment]
Implemented in 2.0, thanks @Meatballs1

**Pull request closed without merging**
